name: template-validate
on:
  workflow_call:
    inputs:
      chdir:
        description: 'The directory to run terraform validate in'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Terraform (${{ inputs.chdir }})
        shell: bash
        run: |
          terraform -chdir=${{ inputs.chdir }} init -backend=false -input=false
          terraform -chdir=${{ inputs.chdir }} validate